server:
  port: 8080
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: SYSTEM
    password: Password1
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: HikariPoolTest
  jpa:
    generate-ddl: true
    # show-sql: true
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.OracleDialect
        use-new-id-generator-mappings: false
    hibernate:
      ddl-auto: update
    open-in-view: true
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    producer:
      batch-size: 5 # Default:16384
      properties:
        linger.ms: 5000 # Default 0